### ISSUE TITLE
Release 0.6.0 to pypi

### ISSUE THREAD

**Issue by eliran1314** [roniemartinez/browsers#128]
Hi,
The last version released to pypi is 0.5.2 and not the latest, can you please release the last version to pypi?
Thanks

**Comment by roniemartinez** [comment]
Thanks for checking on this. It was a workflow failure.
Unfortunately I cannot release that actual tag now. `0.6.0` release is pointed at the current master and should not be available in PyPI.

**Comment by eliran1314** [comment]
Thanks
